DFWeb/views/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectMultipleField
from wtforms.validators import DataRequired
from DFWeb.models import PostTags

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    submit = SubmitField('Post')

class PostAddTagsForm(FlaskForm):
    tags = SelectMultipleField('Select Post Tag(s)', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Add Tags To Post')

    def __init__(self, *args, **kwargs):
        super(PostAddTagsForm, self).__init__(*args, **kwargs)
        self.tags.choices = [(tag.id, tag.tagName) for tag in PostTags.query.all()]

DFWeb/views/posts/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint, current_app)
from flask_login import login_required, current_user
from DFWeb import db
from DFWeb.models import Post, PostTagsPosts, PostTags, TagTypes
from DFWeb.views.posts.forms import PostForm, PostAddTagsForm
from DFWeb.views.posts.utils import (getPosts, getPost, getTags, 
                                    getTagDetails, getPostsByTag)

posts = Blueprint('posts', __name__)

@posts.route('/posts/new', methods=['GET', 'POST'])
@login_required
def newPost():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, 
                    content=request.form.get('editordata'), 
                    user_id=current_user.id)
        db.session.add(post)
        db.session.flush()
        thisPostID = post.id
        db.session.commit()
        return redirect(url_for('posts.addPostTags', thisPostID=thisPostID))
        #flash('Post has been created!', 'success')
        #return redirect(url_for('main.home'))
    kwargs = {
        'form': form
    }
    return render_template('posts/newPost.html', **kwargs)

@posts.route('/posts/addPostTags', methods=['GET', 'POST'])
def addPostTags():
    form = PostAddTagsForm()
    thisPostID = request.args['thisPostID']
    if form.validate_on_submit():
        tags = form.tags.data
        if tags:
            for tag in tags:
                postTags = PostTagsPosts(post_id=thisPostID, tag_id=tag)
                db.session.add(postTags)
            db.session.commit()
        return redirect(url_for('posts.viewPosts'))
    kwargs = {
        'form': form
    }
    return render_template('posts/addPostTags.html', **kwargs)

@posts.route('/posts/viewall', methods=['GET'])
def viewPosts():
    page = request.args.get('page', 1, type=int)
    allPostsData = getPosts(page)
    kwargs = {
        'allPosts': allPostsData['posts'],
        'postTags': allPostsData['postTags']
    }
    return render_template('posts/viewPosts.html', **kwargs)

@posts.route('/posts/view/<postID>', methods=['GET'])
def viewPost(postID):
    post = getPost(postID)
    postTagsIDs = [tag.tag_id for tag in post.postTagsR.all()]
    tagsForPost = getTagDetails(postTagsIDs)
    kwargs = {
        'post': post,
        'tagsForPost': tagsForPost
    }
    return render_template('posts/viewPost.html', **kwargs)

@posts.route('/posts/viewByTag/<tagName>')
def viewPostsByTag(tagName):
    print(tagName)
    page = request.args.get('page', 1, type=int)
    taggedPosts = getPostsByTag(tagName, page)
    kwargs = {
        'allPosts': taggedPosts['posts'],
        'postTags': taggedPosts['postTags'],
        'tagName': tagName
    }
    return render_template('posts/viewPostsByTags.html', **kwargs)

DFWeb/templates/posts/addPostTags.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <legend class="border-bottom mb-4 pt-2">
        Add Tags To Post
    </legend>
    <p>Please select all tags related to this post.</p>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.tags.label(class="form-control-label") }}
                {% if form.tags.errors %}
                    {{ form.tags(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.tags.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.tags(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group pt-4">
            {{ form.submit(class="btn btn-outline-info", multiple="multiple", id="multiSelect") }}
        </div>
    </form>
</div>

{% endblock content %}

DFWeb/templates/posts/newPost.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <legend class="border-bottom mb-4 pt-2">
        Add New Post
    </legend>
    <p>Here is an example feature for adding posts to a webpage.</p>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="pb-2">
            <h8>Content</h8>
        </div>
        <textarea id="summernote" name="editordata"></textarea>
        <div class="form-group pt-4">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<script>
    $('#summernote').summernote({
      placeholder: 'Enter Post Content Here',
      tabsize: 2,
      height: 400
    });
</script>
{% endblock content %}

DFWeb/templates/posts/viewPost.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section pt-2">
    <div class="container pt-2"></div>
        <div class="container-fluid pb-2 pt-4 border rounded">
            <div class="media">
                <div class="media-left">
                    <img src="{{url_for('static', filename='pics/profiles/'+post.author.profilePic)}}" class="media-object rounded-circle border" style="width:60px">
                </div>
                <div class="media-body pl-2">
                    <h4 class="mt-0">{{ post.title }}</h4>
                    <div>
                        {{ post.content|safe }}
                    </div>
                    <div>
                        {% for tag in tagsForPost %}
                            <span class="badge {{ tag[1].tagType }}">{{ tag[0].tagName }}</span>
                        {% endfor %}
                    </div>
                    <small class="text-muted">
                        <i>
                            Created By: {{ post.author.username }} on {{ post.date_posted.strftime('%d-%m-%Y') }} 
                        </i>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

DFWeb/templates/posts/viewPosts.html
{% extends "layout.html" %}
{% block content %}
<div class="container pt-4">
    <h2>Website Posts</h2>
    <p>Here is an example of a website user posting feature.</p>
    <p>
        General users of the site cannot access the CMS for the website, 
        it is using the <a href="https://summernote.org/" target="_blanks">summernote</a>
        wysiwyg (what you see is what you get) editor.
    </p>
    <p>
        Posts are then saved to a database as html to be loaded and 
        displayed as required.
    </p>
    <p>
        Posts can also be tagged with key identifiers to aid end users in 
        searching through a sites content. 
    </p>
    <p>
            The tags are displayed as Badges: 
        <span class="badge badge-primary">Example</span>
    </p>
    <p>
        To arrange access to use the CMS within this site please send me an  
        <a href="mailto:dfenwick138@gmail.com">email</a>.
    </p>
</div>
<div class="content-section pt-2">
    
    {% for post in allPosts.items %}
        <div class="container pt-2">
            <div class="container-fluid pb-2 pt-4">
                <div class="media">
                    <div class="media-left">
                        <img src="{{url_for('static', filename='pics/profiles/'+post.author.profilePic)}}" class="media-object rounded-circle border" style="width:60px">
                    </div>
                    <div class="media-body pl-2">
                        <h4 class="mt-0"><a href="{{(url_for('posts.viewPost', postID=post.id|string))}}">{{ post.title }}</a></h4>
                        {{ post.content|safe }}
                        <small class="text-muted">
                            <div>
                                {% for tag in postTags %}
                                    {% if tag.PostTagsPosts.post_id ==  post.id %}
                                        <a href="{{(url_for('posts.viewPostsByTag', tagName=tag.PostTags.tagName))}}" class="badge {{ tag.TagTypes.tagType }}">{{ tag.PostTags.tagName }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <i>
                                Created By: {{ post.author.username }} on {{ post.date_posted.strftime('%d-%m-%Y') }} 
                            </i>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    
    <div class="container-fluid text-center pt-2">
        {% for page_num in allPosts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if allPosts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('posts.viewPosts', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.viewPosts', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock content %}

DFWeb/templates/posts/viewPostsByTags.html
{% extends "layout.html" %}
{% block content %}
<div class="container pt-4">
    <h2>Website Posts Tagged With {{ tagName }}</h2>
</div>
<div class="content-section pt-2">
    
    {% for post in allPosts.items %}
        <div class="container pt-2">
            <div class="container-fluid pb-2 pt-4">
                <div class="media">
                    <div class="media-left">
                        <img src="{{url_for('static', filename='pics/profiles/'+post.Post.author.profilePic)}}" class="media-object rounded-circle border" style="width:60px">
                    </div>
                    <div class="media-body pl-2">
                        <h4 class="mt-0"><a href="{{(url_for('posts.viewPost', postID=post.Post.id|string))}}">{{ post.Post.title }}</a></h4>
                        {{ post.Post.content|safe }}
                        <small class="text-muted">
                            <div>
                                {% for tag in postTags %}
                                    {% if tag.PostTagsPosts.post_id ==  post.Post.id %}
                                        <a href="{{(url_for('posts.viewPostsByTag', tagName=tag.PostTags.tagName))}}" class="badge {{ tag.TagTypes.tagType }}">{{ tag.PostTags.tagName }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <i>
                                Created By: {{ post.Post.author.username }} on {{ post.Post.date_posted.strftime('%d-%m-%Y') }} 
                            </i>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    
    <div class="container-fluid text-center pt-2">
        {% for page_num in allPosts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if allPosts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('posts.viewPosts', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.viewPosts', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock content %}