DFWeb/views/admin/routes.py
from flask import (render_template, Blueprint, current_app, redirect, url_for,
                    flash, request)
from flask_login import login_user, current_user, logout_user, login_required
from DFWeb.models import User, FPCarousel, PostTags, TagTypes, Certs
from DFWeb import db, bcrypt
from DFWeb.views.admin.forms import (LoginForm, CarouselDeleteForm, 
                                    CarouselUpdateForm, UpdateProfileForm,
                                    UpdatePostTagsForm, AddNewAdminForm,
                                    AddNewCertificateForm, DeletePostTagsForm)
from DFWeb.views.admin.utils import saveImg, saveFile, getAllTags

admin = Blueprint('admin', __name__)


@admin.route('/admin/login', methods=['GET', 'POST'])
def adminLogin():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('You Are Now Logged In', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful, Please Check Email and Password', 'danger')
    kwargs = {
        'form': form
    }
    return render_template('admin/adminLogin.html', **kwargs)


@admin.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@admin.route('/admin/update/carousel', methods=['GET', 'POST'])
@login_required
def updateCarousel():
    form = CarouselUpdateForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                filename = saveImg(form.photo.data, 'CAROUSEL_DIR', 
                                    resizeImg=True)
                
                carouselItem = FPCarousel(filename=filename, 
                                        title=form.title.data, 
                                        small_text=form.small_text.data \
                                            if form.small_text.data != '' else '...', 
                                        user_id=current_user.id)
                db.session.add(carouselItem)
            except Exception as e:
                flash(f'Image Cannot Be Added {e}', 'danger')
                return redirect(url_for('admin.updateCarousel'))
            try:
                db.session.commit()
                flash('Image Added', 'success')
            except Exception as e:
                flash(f'Image Not Added', 'danger')
                return redirect(url_for('admin.updateCarousel'))
            return redirect(url_for('admin.updateCarousel'))
   
    kwargs = {
        'form': form,
    }
    return render_template('admin/updateCarousel.html', **kwargs)


@admin.route('/admin/delete/carousel', methods=['GET', 'POST'])
@login_required
def deleteCarousel():
    form = CarouselDeleteForm()
    fpCarouselItems = FPCarousel.query.all()
    if request.method == 'POST':
        if form.validate_on_submit():
            imgVals = request.form.getlist('checkSelect')
            for imgID in imgVals:
                FPCarousel.deleteImg(imgID)
            flash('Image Deleted', 'success')
            # Image still needs to be deleted from folder
            return redirect(url_for('admin.deleteCarousel'))
   
    kwargs = {
        'form': form,
        'fpCarouselItems': fpCarouselItems
    }
    return render_template('admin/deleteCarousel.html', **kwargs)


@admin.route('/admin/update/profile', methods=['GET', 'POST'])
@login_required
def updateProfile():
    form = UpdateProfileForm()
    userData = User.query.filter_by(id=current_user.id).first()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.username.data:
                current_user.username = form.username.data
            if form.email.data:
                current_user.email = form.email.data
            if form.profilePic.data:
                filename = saveImg(form.profilePic.data, 'PROFILE_DIR')
                current_user.profilePic = filename
            db.session.commit()
            flash('Your account has been updated!', 'success')
            return redirect(url_for('admin.updateProfile'))      
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    kwargs = {
        'form': form,
        'userData': userData
    }
    return render_template('admin/updateProfile.html', **kwargs)


@admin.route('/admin/addNewPostTag', methods=['GET', 'POST'])
#@login_required
def addNewPostTags():
    tagTypes = TagTypes.query.all()
    tags = [(tag.id, str(tag.tagType).replace('badge-','').title()) for tag in tagTypes]
    form = UpdatePostTagsForm()
    form.tagType.choices = tags
    allTags = getAllTags()
    if request.method == 'GET':
        kwargs = {
            'form': form,
            'allTags': allTags,
            'tagTypes': tagTypes
        }
        return render_template('admin/addNewPostTags.html', **kwargs)
    elif request.method == 'POST':
        if form.validate_on_submit():
            newTag = PostTags(tagName=form.tagName.data,
                              tagType=form.tagType.data)
            db.session.add(newTag)
            db.session.commit()
            return redirect(url_for('admin.addNewPostTags'))


@admin.route('/admin/delete/postTags', methods=['GET', 'POST'])
@login_required
def deletePostTags():
    form = DeletePostTagsForm()
    allTags = getAllTags()
    print(allTags)
    for tag in allTags:
        print(tag.tagName)
    if request.method == 'GET':
        kwargs = {
            'form': form,
            'allTags': allTags

        }
        return render_template('admin/deletePostTags.html', **kwargs)


@admin.route('/admin/addNewAdmin', methods=['GET', 'POST'])
@login_required
def addAdminUser():
    form = AddNewAdminForm()
    return render_template('admin/addNewAdmin.html', **kwargs)
    

@admin.route('/admin/addNewCert', methods=['GET', 'POST'])
@login_required
def addCertificate():
    form = AddNewCertificateForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            filename = saveFile(form.filename.data, 'CERTS_DIR')
            cert = Certs(filename = filename,
                         title = form.title.data,
                         content = form.content.data)
            db.session.add(cert)
            db.session.commit()
            return redirect(url_for('admin.addCertificate'))
    kwargs = {
        'form': form
    }
    return render_template('admin/addNewCertificate.html', **kwargs)

DFWeb/views/main/routes.py
from flask import (render_template, url_for, flash, redirect, 
                   request, Blueprint, current_app)
from datetime import datetime
from dateutil.relativedelta import relativedelta
from os import listdir
from DFWeb.models import FPCarousel

main = Blueprint('main', __name__)

@main.route("/")
@main.route('/home', methods=['GET'])
def home():
    dtNow = datetime.now()
    bd = datetime(1988, 8, 13)
    sd = datetime(2015, 5, 27)
    age = relativedelta(dtNow, bd).years
    worklength = relativedelta(dtNow, sd).years
    carouselImages = FPCarousel.query.all()
    kwargs = {
        'age': age,
        'worklength': worklength,
        'carouselImages': carouselImages
    }
    return render_template('home.html', **kwargs)

DFWeb/views/posts/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint, current_app)
from flask_login import login_required, current_user
from DFWeb import db
from DFWeb.models import Post, PostTagsPosts, PostTags, TagTypes
from DFWeb.views.posts.forms import PostForm, PostAddTagsForm
from DFWeb.views.posts.utils import (getPosts, getPost, getTags, 
                                    getTagDetails, getPostsByTag)

posts = Blueprint('posts', __name__)

@posts.route('/posts/new', methods=['GET', 'POST'])
@login_required
def newPost():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, 
                    content=request.form.get('editordata'), 
                    user_id=current_user.id)
        db.session.add(post)
        db.session.flush()
        thisPostID = post.id
        db.session.commit()
        return redirect(url_for('posts.addPostTags', thisPostID=thisPostID))
        #flash('Post has been created!', 'success')
        #return redirect(url_for('main.home'))
    kwargs = {
        'form': form
    }
    return render_template('posts/newPost.html', **kwargs)

@posts.route('/posts/addPostTags', methods=['GET', 'POST'])
def addPostTags():
    form = PostAddTagsForm()
    thisPostID = request.args['thisPostID']
    if form.validate_on_submit():
        tags = form.tags.data
        if tags:
            for tag in tags:
                postTags = PostTagsPosts(post_id=thisPostID, tag_id=tag)
                db.session.add(postTags)
            db.session.commit()
        return redirect(url_for('posts.viewPosts'))
    kwargs = {
        'form': form
    }
    return render_template('posts/addPostTags.html', **kwargs)

@posts.route('/posts/viewall', methods=['GET'])
def viewPosts():
    page = request.args.get('page', 1, type=int)
    allPostsData = getPosts(page)
    kwargs = {
        'allPosts': allPostsData['posts'],
        'postTags': allPostsData['postTags']
    }
    return render_template('posts/viewPosts.html', **kwargs)

@posts.route('/posts/view/<postID>', methods=['GET'])
def viewPost(postID):
    post = getPost(postID)
    postTagsIDs = [tag.tag_id for tag in post.postTagsR.all()]
    tagsForPost = getTagDetails(postTagsIDs)
    kwargs = {
        'post': post,
        'tagsForPost': tagsForPost
    }
    return render_template('posts/viewPost.html', **kwargs)

@posts.route('/posts/viewByTag/<tagName>')
def viewPostsByTag(tagName):
    print(tagName)
    page = request.args.get('page', 1, type=int)
    taggedPosts = getPostsByTag(tagName, page)
    kwargs = {
        'allPosts': taggedPosts['posts'],
        'postTags': taggedPosts['postTags'],
        'tagName': tagName
    }
    return render_template('posts/viewPostsByTags.html', **kwargs)

DFWeb/templates/home.html
{% extends "layout.html" %}
{% block content %}

			<div class=" text-center pb-2 pt-4">
				<p class="h1 ">Welcome to my website</p>
				<p>
					I have built this website to practice Python, expand upon my skills, 
					host photos from holidays and some other projects too. 
				</p>
				<p>
					Please feel free to look around.
				</p>
			</div>


			<div id="carouselFP" class="carousel slide pb-4" data-ride="carousel">
				<ol class="carousel-indicators">
				{% for image in carouselImages %}
					<li data-target="#carouselFP" data-slide-to="{{ loop.index-1 }}" class="{% if loop.index == 1 %}active{% endif %}"></li>
				{% endfor %}
				</ol>
				<div class="carousel-inner">
					{% for image in carouselImages %}
						<div class="carousel-item {% if loop.index == 1 %}active{% endif %}">				
							<img class="d-block w-100 rounded border" src="{{url_for('static', filename='pics/carousel/'+image.filename)}}">
							<div class="carousel-caption d-none d-md-block">
								<h2>{{ image.title }}</h2>
								<p>{{ image.small_text }}</p>
							</div>
						</div>
					{% endfor %}
				</div>
				<a class="carousel-control-prev" href="#carouselFP" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselFP" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>


			<div class="card" id="AboutMe">
				<div class="card-body">
					<h5 class="card-title">About Me</h5>
					<p>
						I am Dave Fenwick, {{ age }} years old and have been working with data for the past {{ worklength }} years.
						Having found a way to turn my passion into product a little later than most, I have ensured that my development 
						has maintained a constant and steady progress. Through working in areas involving front end database administration, 
						analytics, reporting, back-end integration, webhooks and APIs I have had a great platform to learn and advance.
					</p>
					<p>
						Utilising Pythons free and open-source environment has enabled me to implement scalable and cost-effective 
						solutions to business problems, quickly and effectively enhancing our offering to our customers. Creating 
						integration components that solve business needs, enabling us to be more productive without having to 
						increase headcount. Programmatically collecting, transforming and unleashing the power of data in an effective 
						manner without having to break the bank to do so.
					</p>
					<p>
						I am currently employed at Charles Kendall, working as an Integration and BI Developer where I am creating Python 
						components to help collect, store and distribute mission critical data across the business. In many cases 
						removing the requirement for additional office tasks when taking on new and differing workloads. Creating 
						end-to-end workflows that enable us to offer our customers best in class prices, work completion times and 
						accuracy. For me information on my work history, take a look at my 
						<a href="https://www.linkedin.com/in/david-fenwick-97b5a6145/">linkedin</a> account.
					</p>
					<p>
						As the carousel may suggest, I also have an interest in photography, wildlife & travel. Please feel free to 
						look through some of the photographs from my travels. There is also a selection of example Python projects that 
						explore some of the areas I have worked in.
					</p>
					<p class="card-text"><small class="text-muted">Last updated 04/12/2019</small></p>
				</div>
				<img src="{{url_for('static', filename='pics/profiles/dfenwick.png')}}" class="rounded mx-auto d-block pb-4" alt="..." width="250">
			</div>
{% endblock content %}

DFWeb/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-150914670-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-150914670-1');
    </script>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='pics/favicon.ico') }}">

    <!-- include libraries(jQuery, bootstrap) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- Summernote, fontawesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
    <script src="https://kit.fontawesome.com/b75358f578.js" crossorigin="anonymous"></script>
    

    <title>Dave Fenwick CV Site</title>
  </head>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.home') }}">DF</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/home#AboutMe">About Me<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('posts.viewPosts') }}">Posts</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Projects
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('projects.thisWebsite')}}">This Website</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('projects.readPDF')}}">Reading PDF Data</a>
            <a class="dropdown-item" href="{{ url_for('projects.writePDF')}}">Writing PDFs</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('projects.weatherAPI')}}">API Weather Tool</a>
            <a class="dropdown-item" href="{{ url_for('projects.publicAPIInput')}}">API Recieving Data</a>
            <a class="dropdown-item" href="{{ url_for('projects.jQueryYoutubeFlikr')}}">Youtube & Flikr API</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('projects.dataDisplay') }}">Data Visualisation</a>
            <a class="dropdown-item" href="{{ url_for('projects.GAPublicView') }}">Google Analytics Data</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('projects.certsDisplay') }}">DataCamp Certificates</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('projects.jQueryExample') }}">jQuery Basic</a>
          </div>
        </li>
      </ul>
      {% if current_user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin Tools</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('admin.updateProfile') }}">Update Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('posts.newPost') }}">Create New Post</a>
            <a class="dropdown-item" href="{{ url_for('admin.addNewPostTags') }}">Create New Post Tag</a>
            <a class="dropdown-item" href="{{ url_for('admin.deletePostTags') }}">Delete Post Tags</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('admin.updateCarousel')}}">Update Carousel Img</a>
            <a class="dropdown-item" href="{{ url_for('admin.deleteCarousel')}}">Delete Carousel Img</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('admin.addCertificate')}}">Add Certificate</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('admin.logout') }}">Logout<span class="sr-only">(current)</span></a>
        </li>
      </ul>
    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('admin.adminLogin') }}">Admin Login</a>
      </li>
    </ul>
    {% endif %}
    </div>
  </nav>
  <body>
    <main class="container">
      <div class="text-center">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          <div class="pt-4"></div>
            {% for category, message in messages %}
              <div class=" alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
      {% block content %}{% endblock %}
    </main>
    
  </body>
  <footer>
      <div id="Contact" class="container pt-4 text-center">
          <div class="row">
            <div class="col-sm">
              <p class="h1">Contact</p>
              <p>Mobile +44 7711 883 646</p>
            </div>
          </div>
          <div class="row">
            <div class="col-sm">
              <a href="mailto:dfenwick138@gmail.com"><i class="fas fa-at fa-4x pr-2"></i></a>
              <a href="https://www.linkedin.com/in/david-fenwick-97b5a6145/" target="_blank"> <i class="fab fa-linkedin fa-4x pr-2"></i></a>
            </div>
          </div>
        </div>
  </footer>
</html>