DFWeb/views/projects/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, RadioField, IntegerField
from wtforms.validators import DataRequired, NumberRange
#from wtforms.widgets import TableWidget

class AlliantsDevTest(FlaskForm):
    searchTerm = StringField('Enter Search Term Please', validators=[DataRequired()])
    vidLength = RadioField('Select Video Length',
                           choices=[('Any', 'Video of any length'),
                           ('Short', 'Short videos'),('Medium', 'Medium videos'),
                           ('Long', 'Long videos')])
    numOfResults = IntegerField('Number of results (1-20)', validators=[DataRequired(),
                                NumberRange(min=1,max=20,
                                message='Please select value between 1 - 20')])
    submit = SubmitField('Search')

DFWeb/views/projects/routes.py
import json
# Problems with PyPDF2 in Ubuntu Server 19.1 and Pythonanywhere.com
#import PyPDF2
import random
from os.path import join
from datetime import datetime
from flask import (render_template, Blueprint, make_response, current_app,
                    request, flash, redirect, url_for, jsonify)
from DFWeb.views.projects.utils import (getCerts, getUserData, getUserWeather, 
                                        getAccessToken, createForecastChart,
                                        getAvocadoData, getIrisData, 
                                        getYoutubeVids, getFlikrImgs,
                                        keyCheck)
from DFWeb.models import APIPosted
from DFWeb.views.projects.forms import AlliantsDevTest
from flask_paginate import Pagination, get_page_parameter, get_page_args


projects = Blueprint('projects', __name__)


# datacamp certicates display
@projects.route('/projects/certs')
def certsDisplay():
    page = request.args.get('page', 1, type=int)
    certs = getCerts(page)
    kwargs = {
        'certs': certs
    }
    return render_template('projects/certs.html', **kwargs)


# individual cert display
@projects.route('/projects/certs/<certName>')
def singleCertDisplay(certName):
    pdf_file = join(current_app.config['CERTS_DIR'], certName)

    with open(pdf_file, 'rb') as pdf:
        binary_pdf = pdf.read()
        response = make_response(binary_pdf)
        response.headers['Content-Type'] = 'application/pdf'
        response.headers['Content-Disposition'] = f'inline; filename={pdf_file}'
        return response


# api tool to get user location based on IP (not very reliable I know)
# and display user weather information
@projects.route('/projects/apiTools/weatherAPI')
def weatherAPI():
    try:
        #userIP = request.headers['X-Real-IP']
        userIP = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)  
    except:
        userIP = request.remote_addr
        flash('Problem Obtaining User IP Adress', 'warning')

    userData = getUserData(userIP)
    weatherData = getUserWeather(userData['city'], userData['country_code'])
    forecastDataPre = getUserWeather(userData['city'], userData['country_code'], 
                                    weather='forecast')
    forecastData = forecastDataPre['list']
    renderChart = createForecastChart(forecastData)

    kwargs = {
        'userData': userData,
        'weatherData': weatherData,
        'renderChart': renderChart
    }
    return render_template('projects/apiWeather.html', **kwargs)


# Display myWebsite data from Google Analytics
@projects.route('/projects/googleAnalytics')
def GAPublicView():
    kwargs = {'ACCESS_TOKEN_FROM_SERVICE_ACCOUNT': getAccessToken()}
    return render_template('projects/googleAnalytics.html', **kwargs)


# Display data from Kaggle in some graphs etc
@projects.route('/projects/dataVis')
def dataDisplay():
    avoData = getAvocadoData()
    kwargs = {
        'avoData': avoData
    }
    return render_template('projects/dataVis.html', **kwargs)


# Display Toast notifications that have been POSTed to website using JSON
@projects.route('/projects/public/api/postAndDisplay', methods=['POST', 'GET'])
def publicAPIInput():
    if request.method == 'POST':
        responce = request.get_json()
        apiData = APIPosted(name=responce['data']['name'],
                            msg=responce['data']['message'])
        db.session.add(apiData)
        db.session.commit()
        return '', 200
        #return redirect(url_for('projects.publicAPIInput'))
    elif request.method == 'GET':
        apiData = APIPosted.query.all()
        kwargs = {
            'apiData': apiData
        }
        return render_template('projects/apiReceive.html', **kwargs)


# Read data from PDF example
@projects.route('/projects/readPDF')
def readPDF():
    # BELOW NOT WORKING IN UBUNTU SERVER OR PYTHON ANYWHERE :(
    #pageData = []
    #with open(current_app.config['EXAMPLE_PDF'], 'rb') as f:
    #    fileReader = PyPDF2.PdfFileReader(f)
    #    numP = fileReader.numPages
    #    for x in range(numP):
    #        page = fileReader.getPage(x)
    #        pageData.append(page.extractText())
    #kwargs = {
    #    'numP': numP,
    #    'pageData': pageData
    #}
    #return render_template('projects/readPDFs.html', **kwargs)
    return render_template('projects/readPDFs.html')


# Read data from PDF example
@projects.route('/projects/writePDF')
def writePDF():
    return render_template('projects/writePDFs.html')


# information about this website and link to git repo
@projects.route('/projects/thisWebsite')
def thisWebsite():
    return render_template('projects/thisWebsite.html')


# work in progress
@projects.route('/projects/ML/irisData')
def displayIrisData():
    irisData = getIrisData()
    kwargs = {
        'irisData': irisData
    }
    return render_template('projects/ML/irisData.html', **kwargs)


# retrieve youtube videos and flikr images
@projects.route('/projects/youtubeFlikr', methods=['GET', 'POST'])
def youtubeFlikr(page=1):
    form = AlliantsDevTest()
    if request.method == 'POST':
        if form.validate_on_submit():
            searchTerm = form.searchTerm.data
            vidLength = str(form.vidLength.data).lower()
            numOfResults = form.numOfResults.data
            youtube = getYoutubeVids(searchTerm,
                                     numOfResults=numOfResults,
                                     vidLength=vidLength)
            flikr = getFlikrImgs(searchTerm)

            #youtubeVids = [vid['id']['videoId'] for vid in youtube['items']]
            #flikrImgs = [img['description'] for img in flikr['items']]
            #flikrImgs = flikrImgs[:numOfResults]
            kwargs = {
                'form': form,
                'youtube': youtube,
                'flikr': flikr
            }
            return render_template('projects/youtubeFlikrAPI.html', **kwargs)
    kwargs = {
        'form': form
    }
    return render_template('projects/youtubeFlikrAPI.html', **kwargs)


# youtube and flikr API
@projects.route('/projects/public/api/ytFlikr', methods=['POST'])
def youtubeFlikrAPI():
    if request.method == 'POST':
        try:
            key = request.headers['api-key']
        except Exception:
            response = jsonify({
                'message': 'API Endpoint for Youtube and Flikr API Services'
                })
            return response, 400
        if keyCheck(key) is True:
            query = request.get_json()
            searchTerm = query['data']['searchTerm']
            youtube = getYoutubeVids(searchTerm)
            flikrTemp = getFlikrImgs(searchTerm)
            flikr = random.choices(flikrTemp['items'], k=3)
            flikrImgs = [img['link'] for img in flikr]
            vidID = youtube['items'][0]['id']['videoId']
            youtubeVideoURL = f'https://www.youtube.com/watch?v={vidID}'
            return jsonify(youtube=youtubeVideoURL, flikr=flikrImgs)
        else:
            response = jsonify({'message':'Failed To Authenticate User'})
            return response, 401


@projects.route('/projects/jQuery/api/ytFlikr', methods=['POST'])
def youtubeFlikrAPI_jQuery():
    if request.method == 'POST':
        query = request.get_json()
        searchTerm = query['data']['searchTerm']
        youtube = getYoutubeVids(searchTerm) 
        flikr = getFlikrImgs(searchTerm)
        return jsonify(youtube=youtube, flikr=flikr)
    else:
        message = {'message': 'Failed To Process Request.'}
        return jsonify(message)


@projects.route('/projects/jQuery/ytFlikr', methods=['GET'])
def jQueryYoutubeFlikr():
    return render_template('projects/youtubeFlikr.html')


@projects.route('/projects/jQuery/basicExample', methods=['GET'])
def jQueryExample():
    return render_template('projects/examplejQuery.html')

DFWeb/templates/projects/apiReceive.html
{% extends "layout.html" %}
{% block content %}

            <script>
                $(document).ready(function(){
                    $('.toast').toast('show');
                });
            </script>

            <h1 class="pt-4">
                Example API Utility
            </h1>
            <p>
                This API example will simply recieve your posted JSON data, store it in a database 
                and display it here as a Toast. The page will need to be refreshed after you have 
                posted your data.
            </p>
            <h6>
                What is a Toast?
            </h6>

            <div role="alert" aria-live="assertive" aria-atomic="true" class="toast" data-autohide="false">
                <div class="toast-header">
                    <strong class="mr-auto">Example Toast!</strong>
                    <small>11 mins ago</small>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    Hello! This is a toast message.
                </div>
            </div>
            <h6>
                POST JSON format:
            </h6>
            <pre><code>
                {
                    'data': {
                        'name': 'YOUR NAME',
                        'message': 'YOUR MESSAGE'
                    }
                }
            </code></pre>
            <h6>
                POST Address:
            </h6>
            <p>dfenwick.me.uk/projects/public/api/postAndDisplay</p>
            <h6>
                Recieved Toast Notifications:
            </h6>
            {% for item in apiData %}
            <div role="alert" aria-live="assertive" aria-atomic="true" class="toast" data-autohide="false">
                <div class="toast-header">
                    <strong class="mr-auto">{{ item.name }}</strong>
                    <small>{{ item.date_posted.strftime('%Y-%m-%d') }}</small>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    {{ item.msg }}
                </div>
            </div>
{% endfor %}
{% endblock content %}

DFWeb/templates/projects/apiWeather.html
{% extends "layout.html" %}
{% block content %}
            <h1 class="pt-4">Here is a simple API tool</h1>
            <p>This tool is using 
                <a href="https://ipstack.com/" target="_blank">IP Stack</a> & 
                <a href="https://openweathermap.org/" target="_blank">Open Weather Map</a>.
            </p>
            <p>
                This website is using your IP address to lookup your rough location, using the IP Stack API. It is 
                then using this location data to get weather data for the area associated with your IP address. 
                When on corporate networks, proxy servers, VPNs etc. this can lead to location and weather data being 
                provided for the area your network is, as opposed to where you are.
            </p>
            {% if None == userData.continent_code %}
                <p>No location data found.</p>
                <p>Using Southampton, UK as location. <img src="http://openweathermap.org/images/flags/gb.png"></p>
                
            {% else %}
                <p>The location data provided by IP Stack.</p>
                <p>{{ userData.city }}</p>
                <p>{{ userData.zip }}</p>
                <p>{{ userData.region_name }}, {{ userData.region_code }}</p>
                <p>{{ userData.country_name }}, {{ userData.country_code }} <img src={{"http://openweathermap.org/images/flags/"+userData.country_code+".png"}}></p>
                <p>{{ userData.continent_name }}, {{ userData.continent_code }}</p>
                <p>http://openweathermap.org/images/flags/{{userData.country_code}}.png</p>
                
            {% endif %}
            <p>
                The Weather in {{ userData.city }} is currently: {{ weatherData.weather[0].main }}
                <img src={{ "http://openweathermap.org/img/wn/"+weatherData.weather[0].icon+"@2x.png" }}>
            </p>
            <p>Temperate: {{ weatherData.main.temp }}°C</p>
            <p>Temperate Min: {{ weatherData.main.temp_min }}°C</p>
            <p>Temperate Max: {{ weatherData.main.temp_max }}°C</p>
            <p>Humidity: {{ weatherData.main.humidity }}%</p>
            <p>Pressure: {{ weatherData.main.pressure }} hpa</p>
            <p>Wind Speed: {{ weatherData.wind.speed }}mps @{{ weatherData.wind.deg }}°</p>
            <p>Cloud Coverage: {{ weatherData.clouds.all }}%</p>
            <p>Sunrise: {{ formatTime(weatherData.sys.sunrise) }}</p>
            <p>Sunset: {{ formatTime(weatherData.sys.sunset) }}</p>

            <h2 class="pb-2 pt-2">Forecast - 5 Days / 3 Hour</h2>
            <div id="chart">
                <embed type="image/svg+xml" src= {{ renderChart|safe }} />
            </div>


{% endblock content %}

DFWeb/templates/projects/certs.html
{% extends "layout.html" %}
{% block content %}

<div class="container pt-4">
    <h1>
        <a href="https://www.datacamp.com/" target="_blank">DataCamp</a> Certificates
    </h1>
    <p>Please find below the DataCamp certificates from a brief subscription I had, with the main intentions of 
        the subscription to sharpen up/pratice and to learn some machine learning concepts etc.</p>
    <p>I have also completed the Neural Networks and Deep Learning course on <a href="https://www.coursera.org/learn/neural-networks-deep-learning" target="_blank">Coursera</a>, the certificate is also included below.</p>
    <div class="accordion pt-1" id="accordionCerts">
        {% for cert in certs.items %}
        <div class="card border-bottom">
            <div class="card-header" id="heading{{ loop.index0 }}">
                <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse{{ loop.index0 }}" aria-expanded="true" aria-controls="collapse{{ loop.index0 }}">
                    {{ cert.title }}
                </button>
                </h2>
            </div>

            <div id="collapse{{ loop.index0 }}" class="collapse" aria-labelledby="heading{{ loop.index0 }}" data-parent="#accordionCerts">
                <div class="card-body">
                    <p>Click to view <a href="/projects/certs/{{ cert.filename }}" target="_blank">{{ cert.title }}</a> 
                    </p>
                    <p>{{ cert.content }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="container text-center pt-2">
            {% if certs.prev_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('projects.certsDisplay', page=certs.prev_num) }}">Prev</a>
            {% endif %}
            {% for page_num in certs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if certs.page == page_num %}
                        <a class="btn btn-info mb-4" href="{{ url_for('projects.certsDisplay', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for('projects.certsDisplay', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
            {% if certs.next_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('projects.certsDisplay', page=certs.next_num) }}">Next</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

DFWeb/templates/projects/dataVis.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

<div class="container">
    <h1 class="pt-4">Avocado Prices Data</h1>
    <h6>Historical data on avocado prices and sales volume in multiple US markets</h6>
    <p>
        This data has been obtained from 
        <a href="https://www.kaggle.com/neuromusic/avocado-prices/data" taget="_blank">Kaggle</a>.
        This page is more of an example of how data can be distributed and consumed from a web based
        Python platform, as opposed to an actual in-depth discovery of Avocados sales in the US.
    </p>
</div>
    <table id="table_id" class="display" style="width:100%">
        <thead>
            <tr>												
                <th>Date</th>
                <th>AveragePrice</th>
                <th>Total Volume</th>
                <th>4046</th>
                <th>4225</th>
                <th>4770</th>
                <th>Total Bags</th>
                <th>Small Bags</th>
                <th>Large Bags</th>
                <th>XLarge Bags</th>
                <th>type</th>
                <th>year</th>
                <th>region</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Date</th>
                <th>AveragePrice</th>
                <th>Total Volume</th>
                <th>4046</th>
                <th>4225</th>
                <th>4770</th>
                <th>Total Bags</th>
                <th>Small Bags</th>
                <th>Large Bags</th>
                <th>XLarge Bags</th>
                <th>type</th>
                <th>year</th>
                <th>region</th>
            </tr>
        </tfoot>
    </table>
<div class="container">
    <div class="pt-2">
        <h5>Analysis of Avocado Prices</h5>
        <h6>Relevant Columns In Dataset:</h6>
        <ul>
            <li>Date - The date of the observation</li>
            <li>AveragePrice - the average price of a single avocado</li>
            <li>type - conventional or organic</li>
            <li>year - the year</li>
            <li>Region - the city or region of the observation</li>
            <li>Total Volume - Total number of avocados sold</li>
            <li>4046 - Total number of avocados with PLU 4046 sold</li>
            <li>4225 - Total number of avocados with PLU 4225 sold</li>
            <li>4770 - Total number of avocados with PLU 4770 sold</li>
        </ul>
    </div>
    <div>
        <p>
            So we have had a little look at the data and understand what data each column holds, 
            lets start taking a deeper look at some of the more relevant data. I will be aggregating 
            by month regularly to reduce noise and increase clarity.
        </p>
        <h6>Region:</h6>
        <h7>All regions in our data.</h7>
        <p>
            {% for location in avoData.uniqueRegion %}
                {{ location }}
            {% endfor %}
        </p>
        <p>
            There appears to be some pre-aggregated data, with regions like 
            <b>
                {% for location in avoData.preAggedRegions %}
                    {{ location }}
                {% endfor %}
            </b>.
            For the purposes of this demonstration I will leave the data as it is and 
            treat each line as granular entries.
        </p>
        <p>
            The region with the highest Average Price at a single point in time is 
            <b>{{ avoData.dfHighPriceReg[0] }}</b> and this was achieved on <b>{{ avoData.dfHighPriceReg[1] }}</b>.
        </p>
        <p>
            The region with the overall highest Average Price is PLACEHOLDER
        </p>
        <p>
            We will revisit why the high average prices in certain regions is so high as we 
            progress and also why it's not important, for now we can note that the type of Avocados 
            that see the highest Average Price is Organic.
        </p>
        <h6>Date:</h6>
        <p>The date range in this data is: <b>{{ avoData.dateMin }}</b> to <b>{{ avoData.dateMax }}</b></p>
        <h6>Average Price:</h6>
        <ul>
            <li>Actual Avg: ${{ avoData.avgPrice }}</li>
            <li>Min AP: ${{ avoData.avgPriceMin|float|round(2) }}</li>
            <li>Max AP: ${{ avoData.avgPriceMax|float|round(2) }}</li>
            <li>Std Dev: ${{ avoData.std|float|round(2) }}</li>
            <li>Organic AP: ${{ avoData.organicAP|float|round(2) }}</li>
            <li>Conventional AP: ${{ avoData.convAP|float|round(2) }}</li>
            <li>Type AP Diff: ${{ avoData.organicAP-avoData.convAP|float|round(2) }} </li>
            <li>Organic AP % Diff: {{ (((avoData.organicAP-avoData.convAP)/avoData.organicAP)|float|round(2) * 100)|int }}%</li>
        </ul>
        <div id="chart1" class="rounded">
            <embed type="image/svg+xml" src= {{ avoData.boxPlotR|safe }} />
        </div>
        <p>
            The inter quartile range on the box plot shows us that out data is distributed relatively 
            normally and that working with data that is not skewed. We also see that the outlier average
            prices have relatively little impact on the data and that they are contained to the Organic type. 
            So we can proceed without concern on that front and with a view to understanding the disparity 
            between organic and conventional.
        </p>
        <div id="chart1">
            <embed type="image/svg+xml" src= {{ avoData.lineChart1R|safe }} />
        </div>
        <p>
            The average price of Organic Avocados is on average 30% less expensive than 
            Conventional, however the average price of Avocados is barely influenced by the less expensive 
            organic option. This is telling us that the sales of Organic pale in comparison to Conventional.
        </p>
        <p>
            With Conventional Total Volume <b>{{ "{:,}".format(avoData.conTot) }}</b>
            avocados sold and Organic Total Volume of <b>{{ "{:,}".format(avoData.orgTot) }}</b>.
            We can clearly see that the Conventional type far outsells the Organic with
            <b>{{ ((avoData.conTot/(avoData.conTot+avoData.orgTot))*100)|round(2) }}%</b> 
            of the volume sold being the Conventional type.
        </p>
        <p>
            This also helps us shed some light on why the relatively high average price of Organic 
            avocados in certain regions has little to no impact on overall averages.
        </p>
        <p>
            It becomes apparent when looking at the Avg or Conventional data alone on the graph, that 
            there appears to be a seasonal spike in prices during and leading to the month of February. 
            Something for us to take a closer look at next.
        </p>
        <div id="chart1" class="rounded">
            <embed type="image/svg+xml" src= {{ avoData.lineChart2R|safe }} />
        </div>
        <p>
            Our overall graph clearly shows us the seasonality of the sales of Avocaods, that the most favourable 
            month to consume/buy is February, with January, May & December also being good months to buy. 
            We can also see that conversely, during and towards the end of the summer months is when total 
            volume sold is declining as pricing is increasing. With October being the worst month, on average, to 
            buy avocados.
        </p>
        <p>
            As we have interactive graphs, lets use them. The below graph is messy, feel free to untick specific 
            years to get a year by year break down.
        </p>
        <div id="chart1" class="rounded">
            <embed type="image/svg+xml" src= {{ avoData.lineChart3R|safe }} />
        </div>
    </div>
</div>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#table_id').DataTable( {
            "paging":   true,
            "ordering": true,
            "info":     true,
            "ajax": "/static/data/avocado.txt"
        } );
    } );
</script>

{% endblock content %}

DFWeb/templates/projects/examplejQuery.html
{% extends "layout.html" %}
{% block content %}

<div class="container pt-4">
    <h2 class="border-bottom mb-4">
        Example jQuery Page
    </h2>
    <p class="pt-2">
        jQuery is a fast, lightweight JavaScript library that has many features based on the 
        "write less, do more" principle. jQuery really comes into it's own when using API endpoints 
        on the web server.
    </p>
    <p>
        Below is a simple example of jQuery, it is amending the text into the "output" paragraph when you 
        click submit.
    </p>
    <p>
        The <a href="/projects/jQuery/ytFlikr">Youtube Flikr API example</a> is using jQuery to fetch data 
        from an API endpoint within the server to display to the user.
    </p>
    <form id="exampleForm">
        <div class="form-group">
            <label>Input Name</label>
            <input required type="text" class="form-control" id="name" placeholder="Enter Your Name Please">
        </div>
        <button id="button" class="btn btn-primary" >Say Hello!</button>
    </form>
    <p id="output" class="pt-2"></p>
</div>

<script>
    $(function() {
        $("#exampleForm").submit(function(e) {
            e.preventDefault();
        });
        $("#output").hide()
        $("#button").click(function() {
            var hello = "Hello ";
            var name = $("#name").val();
            var output = hello.concat(name);
            if (name != "") {
                $("#output").text(output).slideToggle(300);
            };
        });
    });
</script>

{% endblock content %}

DFWeb/templates/projects/googleAnalytics.html
{% extends "layout.html" %}
{% block content %}

<script>
    (function(w,d,s,g,js,fs){
        g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(f){this.q.push(f);}};
        js=d.createElement(s);fs=d.getElementsByTagName(s)[0];
        js.src='https://apis.google.com/js/platform.js';
        fs.parentNode.insertBefore(js,fs);js.onload=function(){g.load('analytics');};
    }(window,document,'script'));
</script>
<script>
    gapi.analytics.ready(function() {
    
        /**
        * Authorize the user with an access token obtained server side.
        */
        gapi.analytics.auth.authorize({
        'serverAuth': {
            'access_token': '{{ ACCESS_TOKEN_FROM_SERVICE_ACCOUNT }}'
        }
        });
    
    
        /**
        * Creates a new DataChart instance showing sessions over the past 30 days.
        * It will be rendered inside an element with the id "chart-1-container".
        */
        var dataChart1 = new gapi.analytics.googleCharts.DataChart({
        query: {
            'ids': 'ga:204701187', // <-- Replace with the ids value for your view.
            'start-date': '30daysAgo',
            'end-date': 'yesterday',
            'metrics': 'ga:sessions,ga:users',
            'dimensions': 'ga:date'
        },
        chart: {
            'container': 'chart-1-container',
            'type': 'LINE',
            'options': {
            'width': '100%'
            }
        }
        });
        dataChart1.execute();
    
    
        /**
        * Creates a new DataChart instance showing top 5 most popular demos/tools
        * amongst returning users only.
        * It will be rendered inside an element with the id "chart-2-container".
        */
        var dataChart2 = new gapi.analytics.googleCharts.DataChart({
        query: {
            'ids': 'ga:204701187', // <-- Replace with the ids value for your view.
            'start-date': '30daysAgo',
            'end-date': 'yesterday',
            'metrics': 'ga:pageviews',
            'dimensions': 'ga:pagePathLevel1',
            'sort': '-ga:pageviews',
            'filters': 'ga:pagePathLevel1!=/',
            'max-results': 7
        },
        chart: {
            'container': 'chart-2-container',
            'type': 'PIE',
            'options': {
            'width': '100%',
            'pieHole': 4/9,
            }
        }
        });
        dataChart2.execute();
    
    });
</script>

<div class="container">
    <h1 class="pt-4">Google Analytics</h1>
    <h6>
        Implementation of Google Analytics graphs with server-side authentication. 
    </h6>
    <p>
        This could for example be locked within a website for only admin accounts to access 
        or left open for the public to view.
    </p>
    <p>
        To ammend the queries that create the graphs, 
        <a href="https://ga-dev-tools.appspot.com/query-explorer/" target="_blank">Query Explorer</a>
        is a useful tool for ascertaining attribute names and previewing data before changing the 
        JavaScript driving these graphs. I followed 
        <a href="https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/" target="_blank">this</a> 
        guide to add this functionality to this website.
    </p>
    <div id="chart-1-container"></div>
    <div id="chart-2-container"></div>
</div>

{% endblock content %}

DFWeb/templates/projects/thisWebsite.html
{% extends "layout.html" %}
{% block content %}

<h1 class="pt-4">
    About this website
</h1>
<p>
    This website was built using the Python 
    <a href="https://pypi.org/project/Flask/" target="_blank">Flask</a> 
    framework and <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a>.
    I am also using the <a href="https://summernote.org/" target="_blank">summernote</a> 
    wysiwyg editor for creating posts.
</p>
<p>
    The website is hosted on a <a href="https://www.virtualbox.org/" target="_blank">
    VirtualBox VM</a> running 
    <a href="https://ubuntu.com/download/server" target="_blank">
    Ubuntu Server 19.1</a>,
    <a href="https://www.nginx.com/" target="_blank">
    nginx</a> & 
    <a href="https://gunicorn.org/" target="_blank">
    gunicorn.</a>
</p>
<p>
    For a more indepth please take a look at the 
<a href="https://bitbucket.org/Dayvinho/mywebsite/src/master/" target="_blank">Git</a> or 
<pre><code>git clone https://Dayvinho@bitbucket.org/Dayvinho/mywebsite.git</code></pre>
</p>
<h2>
    Currently Offline on Ubuntu Server
</h2>
<p>
    I am currently working on hosting this website on a Raspberry Pi 4 and also integrating 
    a mesh webcam solution as a potential offering for a charity I would like to work with 
    in the future.
</p>
{% endblock content %}